package com.elector.Enums;

public enum ConfigEnum {
    site_name,
    site_url,
    google_maps_api_key,
    email_reply_to,
    send_emails,
    path_to_voters_books,
    sms_service_username,
    sms_service_password,
    allow_send_sms,
    gmail_user_name,
    gmail_password,
    prod,
    sms_api_username,
    sms_api_password,
    sms_api_token,
    new_sms_api_username,
    new_sms_api_password,
    ram_reach_gb_alert,
    oids_to_log,
    sales_contacts,
    send_highest_performance_activist_notification,
    is_allowed_ip,
    log_beans_names,
    oids_to_debug,
    clear_sessions_task,
    enable_logging_aspect,
    allowed_general_ips,
    allowed_super_admin_ips,
    send_sms_on_new_super_admin_ip,
    log_election_day_service_requests,
    use_election_day_in_memory_service,
    election_day_in_memory_service,
    use_voters_in_memory_service,
    voters_in_memory_service,
    general_jobs_service,
    sms_service,
    path_to_desktop,
    elector_url,
    minutes_to_get_recent_activists_voters_mappings,
    minutes_to_get_recent_callers,
    minutes_recent_requests,
    active_jobs,
    active_job_count_campaign_clients,
    active_job_database_connections_monitor,
    active_job_data_daily,
    active_job_drives,
    active_job_google_maps,
    active_job_manage_birthdays,
    active_job_notifications,
    active_job_save_requests_data,
    active_job_share_observers_data,
    active_job_voters_manipulations,
    active_job_manage_ballot_boxes,
    active_job_vote_status,
    reports_url,
    minimal_android_version,
    minimal_ios_version,
    ping_interval_minutes,
    allow_pinging,
    allow_service_down_reminder,
    service_down_reminder_interval_minutes,
    group_list_warning_sms




}
